version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    user: kibana
    restart: unless-stopped
    ports:
      - 8000:5601
    network_mode: "bridge"
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    user: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: "bridge"
    environment: 
      - discovery.type=single-node
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.0.1
    container_name: apm-server
    user: apm-server
    restart: unless-stopped
    ports:
      - 8200:8200
    network_mode: "bridge"
    links:
      - elasticsearch
