version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: root
    ports:
      - 7020:3000
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
