version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    user: postgres
    restart: unless-stopped
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - pg-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: "bridge"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
volumes:
  pg-storage:
